package com.cybercad.billing.domain.conn;
// Generated Aug 15, 2015 1:12:49 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConnStatus generated by hbm2java
 */
@Entity
@Table(name="conn_status"
    ,catalog="billing"
)
public class ConnStatus  implements java.io.Serializable {


     private Integer id;
     private Integer connId;
     private Double currentReading;
     private Double currentBalance;
     private Double currentAverage;
     private Date prevReadDate;
     private Set<Connection> connections = new HashSet<Connection>(0);

    public ConnStatus() {
    }

    public ConnStatus(Integer connId, Double currentReading, Double currentBalance, Double currentAverage, Date prevReadDate, Set<Connection> connections) {
       this.connId = connId;
       this.currentReading = currentReading;
       this.currentBalance = currentBalance;
       this.currentAverage = currentAverage;
       this.prevReadDate = prevReadDate;
       this.connections = connections;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="conn_id")
    public Integer getConnId() {
        return this.connId;
    }
    
    public void setConnId(Integer connId) {
        this.connId = connId;
    }

    
    @Column(name="current_reading", precision=22, scale=0)
    public Double getCurrentReading() {
        return this.currentReading;
    }
    
    public void setCurrentReading(Double currentReading) {
        this.currentReading = currentReading;
    }

    
    @Column(name="current_balance", precision=22, scale=0)
    public Double getCurrentBalance() {
        return this.currentBalance;
    }
    
    public void setCurrentBalance(Double currentBalance) {
        this.currentBalance = currentBalance;
    }

    
    @Column(name="current_average", precision=22, scale=0)
    public Double getCurrentAverage() {
        return this.currentAverage;
    }
    
    public void setCurrentAverage(Double currentAverage) {
        this.currentAverage = currentAverage;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="prev_read_date", length=19)
    public Date getPrevReadDate() {
        return this.prevReadDate;
    }
    
    public void setPrevReadDate(Date prevReadDate) {
        this.prevReadDate = prevReadDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="connStatus")
    public Set<Connection> getConnections() {
        return this.connections;
    }
    
    public void setConnections(Set<Connection> connections) {
        this.connections = connections;
    }




}


