package com.cybercad.billing.domain.conn.payment;
// Generated 23 Sep, 2015 4:46:26 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentType generated by hbm2java
 */
@Entity
@Table(name="payment_type"
    ,catalog="billing"
)
public class PaymentType  implements java.io.Serializable {


     private Integer id;
     private String desciption;
     private Set<Payment> payments = new HashSet<Payment>(0);

    public PaymentType() {
    }

    public PaymentType(String desciption, Set<Payment> payments) {
       this.desciption = desciption;
       this.payments = payments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="desciption", length=100)
    public String getDesciption() {
        return this.desciption;
    }
    
    public void setDesciption(String desciption) {
        this.desciption = desciption;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paymentType")
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }




}


