package com.cybercad.billing.domain;
// Generated 13 Aug, 2015 2:58:27 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.cybercad.billing.domain.conn.Connection;
import com.cybercad.billing.domain.people.Consumer;

/**
 * ConsConn generated by hbm2java
 */
@Entity
@Table(name="cons_conn"
    ,catalog="billing"
)
public class ConsConn  implements java.io.Serializable {


     private int id;
     private Consumer consumer;
     private Connection connection;
     private Date startDate;
     private Date endDate;

    public ConsConn() {
    }

	
    public ConsConn(int id, Consumer consumer, Connection connection) {
        this.id = id;
        this.consumer = consumer;
        this.connection = connection;
    }
    public ConsConn(int id, Consumer consumer, Connection connection, Date startDate, Date endDate) {
       this.id = id;
       this.consumer = consumer;
       this.connection = connection;
       this.startDate = startDate;
       this.endDate = endDate;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="consumer_id", nullable=false)
    public Consumer getConsumer() {
        return this.consumer;
    }
    
    public void setConsumer(Consumer consumer) {
        this.consumer = consumer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="connection_id", nullable=false)
    public Connection getConnection() {
        return this.connection;
    }
    
    public void setConnection(Connection connection) {
        this.connection = connection;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="end_date", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}


