package com.cybercad.billing.domain.conn;

import org.springframework.data.repository.PagingAndSortingRepository;

/**
 * @author shreyas
 * 
 *         This interface represents the collection of all connections in the
 *         database. Look at the methods in the CrudRepository interface to find
 *         out what already exists.
 * 
 *         An implementation for this interface will be auto generated by the
 *         framework at runtime. Hence no need to create a implementation class
 *
 */
public interface ConnectionRepository extends
		PagingAndSortingRepository<Connection, Integer> {

}
