package com.cybercad.billing.domain.devices;
// Generated 23 Sep, 2015 4:46:26 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MeterRent generated by hbm2java
 */
@Entity
@Table(name="meter_rent"
    ,catalog="billing"
)
public class MeterRent  implements java.io.Serializable {


     private Integer id;
     private Date startDate;
     private Date endDate;
     private Double rentPerDay;
     private Boolean active;
     private Set<MeterType> meterTypes = new HashSet<MeterType>(0);

    public MeterRent() {
    }

    public MeterRent(Date startDate, Date endDate, Double rentPerDay, Boolean active, Set<MeterType> meterTypes) {
       this.startDate = startDate;
       this.endDate = endDate;
       this.rentPerDay = rentPerDay;
       this.active = active;
       this.meterTypes = meterTypes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="end_date", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="rent_per_day", precision=22, scale=0)
    public Double getRentPerDay() {
        return this.rentPerDay;
    }
    
    public void setRentPerDay(Double rentPerDay) {
        this.rentPerDay = rentPerDay;
    }

    
    @Column(name="active")
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="meterRent")
    public Set<MeterType> getMeterTypes() {
        return this.meterTypes;
    }
    
    public void setMeterTypes(Set<MeterType> meterTypes) {
        this.meterTypes = meterTypes;
    }




}


