package com.cybercad.billing.domain.devices;
// Generated 23 Sep, 2015 4:46:26 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MeterConditionHistory generated by hbm2java
 */
@Entity
@Table(name="meter_condition_history"
    ,catalog="billing"
)
public class MeterConditionHistory  implements java.io.Serializable {


     private int id;
     private Meter meter;
     private MeterStatus meterStatus;
     private Date startDate;
     private Date endDate;

    public MeterConditionHistory() {
    }

	
    public MeterConditionHistory(int id, Meter meter, MeterStatus meterStatus, Date startDate) {
        this.id = id;
        this.meter = meter;
        this.meterStatus = meterStatus;
        this.startDate = startDate;
    }
    public MeterConditionHistory(int id, Meter meter, MeterStatus meterStatus, Date startDate, Date endDate) {
       this.id = id;
       this.meter = meter;
       this.meterStatus = meterStatus;
       this.startDate = startDate;
       this.endDate = endDate;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="meter_id", nullable=false)
    public Meter getMeter() {
        return this.meter;
    }
    
    public void setMeter(Meter meter) {
        this.meter = meter;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="meter_status_id", nullable=false)
    public MeterStatus getMeterStatus() {
        return this.meterStatus;
    }
    
    public void setMeterStatus(MeterStatus meterStatus) {
        this.meterStatus = meterStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_date", nullable=false, length=19)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_date", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}


