package com.cybercad.billing.domain.devices;
// Generated 23 Sep, 2015 4:46:26 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MeterType generated by hbm2java
 */
@Entity
@Table(name="meter_type"
    ,catalog="billing"
)
public class MeterType  implements java.io.Serializable {


     private Integer id;
     private MeterRent meterRent;
     private String description;
     private String size;
     private Set<Meter> meters = new HashSet<Meter>(0);

    public MeterType() {
    }

	
    public MeterType(MeterRent meterRent) {
        this.meterRent = meterRent;
    }
    public MeterType(MeterRent meterRent, String description, String size, Set<Meter> meters) {
       this.meterRent = meterRent;
       this.description = description;
       this.size = size;
       this.meters = meters;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="meter_rent_id", nullable=false)
    public MeterRent getMeterRent() {
        return this.meterRent;
    }
    
    public void setMeterRent(MeterRent meterRent) {
        this.meterRent = meterRent;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="size", length=45)
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="meterType")
    public Set<Meter> getMeters() {
        return this.meters;
    }
    
    public void setMeters(Set<Meter> meters) {
        this.meters = meters;
    }




}


