package com.cybercad.billing.domain.devices;
// Generated 13 Aug, 2015 2:58:27 AM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MeterType generated by hbm2java
 */
@Entity
@Table(name="meter_type"
    ,catalog="billing"
)
public class MeterType  implements java.io.Serializable {


     private Integer id;
     private String description;
     private String size;
     private String rent;
     private Set<Meter> meters = new HashSet<Meter>(0);

    public MeterType() {
    }

    public MeterType(String description, String size, String rent, Set<Meter> meters) {
       this.description = description;
       this.size = size;
       this.rent = rent;
       this.meters = meters;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="size", length=45)
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }

    
    @Column(name="rent", length=45)
    public String getRent() {
        return this.rent;
    }
    
    public void setRent(String rent) {
        this.rent = rent;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="meterType")
    public Set<Meter> getMeters() {
        return this.meters;
    }
    
    public void setMeters(Set<Meter> meters) {
        this.meters = meters;
    }




}


