package com.cybercad.billing.domain.people;
// Generated 13 Aug, 2015 2:58:27 AM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.cybercad.billing.domain.ConsConn;
import com.cybercad.billing.domain.Prefix;
import com.cybercad.billing.domain.Religion;

/**
 * Consumer generated by hbm2java
 */
@Entity
@Table(name="consumer"
,catalog="billing"
, uniqueConstraints = @UniqueConstraint(columnNames="cons_code") 
		)
public class Consumer  implements java.io.Serializable {
	private int id;
	private String consCode;
	private Set<ConsConn> consConns = new HashSet<ConsConn>(0);
	@ManyToOne
	private Prefix prefix;
	private String consumerName;
	private long mobile;
	private String email;
	@ManyToOne
	private Religion religion;
	public Consumer() {
	}


	public Consumer(int id, String consCode) {
		this.id = id;
		this.consCode = consCode;
	}
	public Consumer(int id, String consCode, Set<ConsConn> consConns) {
		this.id = id;
		this.consCode = consCode;
		this.consConns = consConns;
	}

	public Consumer(int id, String consCode, Set<ConsConn> consConns,
			Prefix prefix, String consumerName, long mobile, String email,
			Religion religion) {
		super();
		this.id = id;
		this.consCode = consCode;
		this.consConns = consConns;
		this.prefix = prefix;
		this.consumerName = consumerName;
		this.mobile = mobile;
		this.email = email;
		this.religion = religion;
	}


	@Id 
	@Column(name="id", unique=true, nullable=false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}


	@Column(name="cons_code", unique=true, nullable=false, length=10)
	public String getConsCode() {
		return this.consCode;
	}

	public void setConsCode(String consCode) {
		this.consCode = consCode;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="consumer")
	public Set<ConsConn> getConsConns() {
		return this.consConns;
	}

	public Prefix getPrefix() {
		return prefix;
	}


	public void setPrefix(Prefix prefix) {
		this.prefix = prefix;
	}


	public String getConsumerName() {
		return consumerName;
	}


	public void setConsumerName(String consumerName) {
		this.consumerName = consumerName;
	}


	public long getMobile() {
		return mobile;
	}


	public void setMobile(long mobile) {
		this.mobile = mobile;
	}


	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}


	public Religion getReligion() {
		return religion;
	}


	public void setReligion(Religion religion) {
		this.religion = religion;
	}


	public void setConsConns(Set<ConsConn> consConns) {
		this.consConns = consConns;
	}




}


