package com.cybercad.billing.domain;
// Generated 13 Aug, 2015 2:58:27 AM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.cybercad.billing.domain.conn.Connection;

/**
 * Constituency generated by hbm2java
 */
@Entity
@Table(name="constituency"
    ,catalog="billing"
)
public class Constituency  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Connection> connections = new HashSet<Connection>(0);

    public Constituency() {
    }

    public Constituency(String name, Set<Connection> connections) {
       this.name = name;
       this.connections = connections;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="constituency")
    public Set<Connection> getConnections() {
        return this.connections;
    }
    
    public void setConnections(Set<Connection> connections) {
        this.connections = connections;
    }




}


