package com.cybercad.billing.domain.tariff;
// Generated 23 Sep, 2015 4:46:26 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.cybercad.billing.domain.conn.ConnectionCategory;

/**
 * TariffClass generated by hbm2java
 */
@Entity
@Table(name="tariff_class"
    ,catalog="billing"
)
public class TariffClass  implements java.io.Serializable {


     private int id;
     private String description;
     private Date activationDate;
     private Date terminationDate;
     private Set<ConnectionCategory> connectionCategories = new HashSet<ConnectionCategory>(0);
     private Set<TariffSlab> tariffSlabs = new HashSet<TariffSlab>(0);

    public TariffClass() {
    }

	
    public TariffClass(int id) {
        this.id = id;
    }
    public TariffClass(int id, String description, Date activationDate, Date terminationDate, Set<ConnectionCategory> connectionCategories, Set<TariffSlab> tariffSlabs) {
       this.id = id;
       this.description = description;
       this.activationDate = activationDate;
       this.terminationDate = terminationDate;
       this.connectionCategories = connectionCategories;
       this.tariffSlabs = tariffSlabs;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="activation_date", length=10)
    public Date getActivationDate() {
        return this.activationDate;
    }
    
    public void setActivationDate(Date activationDate) {
        this.activationDate = activationDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="termination_date", length=10)
    public Date getTerminationDate() {
        return this.terminationDate;
    }
    
    public void setTerminationDate(Date terminationDate) {
        this.terminationDate = terminationDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tariffClass")
    public Set<ConnectionCategory> getConnectionCategories() {
        return this.connectionCategories;
    }
    
    public void setConnectionCategories(Set<ConnectionCategory> connectionCategories) {
        this.connectionCategories = connectionCategories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tariffClass")
    public Set<TariffSlab> getTariffSlabs() {
        return this.tariffSlabs;
    }
    
    public void setTariffSlabs(Set<TariffSlab> tariffSlabs) {
        this.tariffSlabs = tariffSlabs;
    }




}


