package com.cybercad.billing.domain.conn.reading;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fault generated by hbm2java
 */
@Entity
@Table(name = "fault", catalog = "billing")
public class Fault implements java.io.Serializable {

	private static final long serialVersionUID = -865661221474870967L;
	private Integer id;
	private String description;

	public Fault() {
	}

	public Fault(String description, Set<ConnReading> connReadings) {
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
