package com.cybercad.billing.domain.conn.reading;
// Generated Aug 15, 2015 1:12:49 AM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fault generated by hbm2java
 */
@Entity
@Table(name="fault"
    ,catalog="billing"
)
public class Fault  implements java.io.Serializable {


     private Integer id;
     private String description;
     private Set<ConnReading> connReadings = new HashSet<ConnReading>(0);

    public Fault() {
    }

    public Fault(String description, Set<ConnReading> connReadings) {
       this.description = description;
       this.connReadings = connReadings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fault")
    public Set<ConnReading> getConnReadings() {
        return this.connReadings;
    }
    
    public void setConnReadings(Set<ConnReading> connReadings) {
        this.connReadings = connReadings;
    }




}


