package com.cybercad.billing.domain.people;
// Generated 23 Sep, 2015 4:46:26 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Consumer generated by hbm2java
 */
@Entity
@Table(name="consumer"
    ,catalog="billing"
)
public class Consumer  implements java.io.Serializable {


     private int id;
     private Prefix prefix;
     private Religion religion;
     private String firstName;
     private String middleName;
     private String lastName;
     private Long mobile;
     private String email;
     private Set<ConsConn> consConns = new HashSet<ConsConn>(0);

    public Consumer() {
    }

	
    public Consumer(int id, Prefix prefix, Religion religion) {
        this.id = id;
        this.prefix = prefix;
        this.religion = religion;
    }
    public Consumer(int id, Prefix prefix, Religion religion, String firstName, String middleName, String lastName, Long mobile, String email, Set<ConsConn> consConns) {
       this.id = id;
       this.prefix = prefix;
       this.religion = religion;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.mobile = mobile;
       this.email = email;
       this.consConns = consConns;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prefix_id", nullable=false)
    public Prefix getPrefix() {
        return this.prefix;
    }
    
    public void setPrefix(Prefix prefix) {
        this.prefix = prefix;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="religion_id", nullable=false)
    public Religion getReligion() {
        return this.religion;
    }
    
    public void setReligion(Religion religion) {
        this.religion = religion;
    }

    
    @Column(name="first_name", length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="middle_name", length=45)
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    @Column(name="last_name", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="mobile")
    public Long getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Long mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consumer")
    public Set<ConsConn> getConsConns() {
        return this.consConns;
    }
    
    public void setConsConns(Set<ConsConn> consConns) {
        this.consConns = consConns;
    }




}


