package com.cybercad.billing.domain.people;
// Generated 23 Sep, 2015 4:46:26 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Religion generated by hbm2java
 */
@Entity
@Table(name="religion"
    ,catalog="billing"
)
public class Religion  implements java.io.Serializable {


     private int id;
     private String description;
     private Set<Consumer> consumers = new HashSet<Consumer>(0);

    public Religion() {
    }

	
    public Religion(int id, String description) {
        this.id = id;
        this.description = description;
    }
    public Religion(int id, String description, Set<Consumer> consumers) {
       this.id = id;
       this.description = description;
       this.consumers = consumers;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="description", nullable=false, length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="religion")
    public Set<Consumer> getConsumers() {
        return this.consumers;
    }
    
    public void setConsumers(Set<Consumer> consumers) {
        this.consumers = consumers;
    }




}


