package com.cybercad.billing.domain;
// Generated 13 Aug, 2015 2:58:27 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConnReading generated by hbm2java
 */
@Entity
@Table(name="conn_reading"
    ,catalog="billing"
)
public class ConnReading  implements java.io.Serializable {


     private Integer id;
     private ReadCycle readCycle;
     private Connection connection;
     private Date readDate;
     private Double reading;
     private Double charges;

    public ConnReading() {
    }

	
    public ConnReading(ReadCycle readCycle, Connection connection) {
        this.readCycle = readCycle;
        this.connection = connection;
    }
    public ConnReading(ReadCycle readCycle, Connection connection, Date readDate, Double reading, Double charges) {
       this.readCycle = readCycle;
       this.connection = connection;
       this.readDate = readDate;
       this.reading = reading;
       this.charges = charges;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="read_cycle_id", nullable=false)
    public ReadCycle getReadCycle() {
        return this.readCycle;
    }
    
    public void setReadCycle(ReadCycle readCycle) {
        this.readCycle = readCycle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="connection_id", nullable=false)
    public Connection getConnection() {
        return this.connection;
    }
    
    public void setConnection(Connection connection) {
        this.connection = connection;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="read_date", length=19)
    public Date getReadDate() {
        return this.readDate;
    }
    
    public void setReadDate(Date readDate) {
        this.readDate = readDate;
    }

    
    @Column(name="reading", precision=22, scale=0)
    public Double getReading() {
        return this.reading;
    }
    
    public void setReading(Double reading) {
        this.reading = reading;
    }

    
    @Column(name="charges", precision=22, scale=0)
    public Double getCharges() {
        return this.charges;
    }
    
    public void setCharges(Double charges) {
        this.charges = charges;
    }




}


