package com.cybercad.billing.domain;
// Generated 13 Aug, 2015 2:58:27 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConnPayment generated by hbm2java
 */
@Entity
@Table(name="conn_payment"
    ,catalog="billing"
)
public class ConnPayment  implements java.io.Serializable {


     private Integer id;
     private PaymentType paymentType;
     private Connection connection;
     private Date paymentDate;
     private Double amount;
     private int tellerId;

    public ConnPayment() {
    }

	
    public ConnPayment(PaymentType paymentType, Connection connection, int tellerId) {
        this.paymentType = paymentType;
        this.connection = connection;
        this.tellerId = tellerId;
    }
    public ConnPayment(PaymentType paymentType, Connection connection, Date paymentDate, Double amount, int tellerId) {
       this.paymentType = paymentType;
       this.connection = connection;
       this.paymentDate = paymentDate;
       this.amount = amount;
       this.tellerId = tellerId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="payment_type_id", nullable=false)
    public PaymentType getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(PaymentType paymentType) {
        this.paymentType = paymentType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="connection_id", nullable=false)
    public Connection getConnection() {
        return this.connection;
    }
    
    public void setConnection(Connection connection) {
        this.connection = connection;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="payment_date", length=19)
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    
    @Column(name="amount", precision=22, scale=0)
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    
    @Column(name="teller_id", nullable=false)
    public int getTellerId() {
        return this.tellerId;
    }
    
    public void setTellerId(int tellerId) {
        this.tellerId = tellerId;
    }




}


