package com.cybercad.billing.domain;
// Generated 13 Aug, 2015 2:58:27 AM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Consumer generated by hbm2java
 */
@Entity
@Table(name="consumer"
    ,catalog="billing"
    , uniqueConstraints = @UniqueConstraint(columnNames="cons_code") 
)
public class Consumer  implements java.io.Serializable {


     private int id;
     private String consCode;
     private Set<ConsConn> consConns = new HashSet<ConsConn>(0);

    public Consumer() {
    }

	
    public Consumer(int id, String consCode) {
        this.id = id;
        this.consCode = consCode;
    }
    public Consumer(int id, String consCode, Set<ConsConn> consConns) {
       this.id = id;
       this.consCode = consCode;
       this.consConns = consConns;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="cons_code", unique=true, nullable=false, length=10)
    public String getConsCode() {
        return this.consCode;
    }
    
    public void setConsCode(String consCode) {
        this.consCode = consCode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consumer")
    public Set<ConsConn> getConsConns() {
        return this.consConns;
    }
    
    public void setConsConns(Set<ConsConn> consConns) {
        this.consConns = consConns;
    }




}


