package com.cybercad.billing.domain;
// Generated 13 Aug, 2015 2:58:27 AM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MeterReader generated by hbm2java
 */
@Entity
@Table(name="meter_reader"
    ,catalog="billing"
)
public class MeterReader  implements java.io.Serializable {


     private int id;
     private Set<ReadCycle> readCycles = new HashSet<ReadCycle>(0);
     private Set<Device> devices = new HashSet<Device>(0);

    public MeterReader() {
    }

	
    public MeterReader(int id) {
        this.id = id;
    }
    public MeterReader(int id, Set<ReadCycle> readCycles, Set<Device> devices) {
       this.id = id;
       this.readCycles = readCycles;
       this.devices = devices;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="meterReader")
    public Set<ReadCycle> getReadCycles() {
        return this.readCycles;
    }
    
    public void setReadCycles(Set<ReadCycle> readCycles) {
        this.readCycles = readCycles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="meterReader")
    public Set<Device> getDevices() {
        return this.devices;
    }
    
    public void setDevices(Set<Device> devices) {
        this.devices = devices;
    }




}


