package com.cybercad.billing.domain;
// Generated 13 Aug, 2015 2:58:27 AM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentType generated by hbm2java
 */
@Entity
@Table(name="payment_type"
    ,catalog="billing"
)
public class PaymentType  implements java.io.Serializable {


     private Integer id;
     private String desciption;
     private Set<ConnPayment> connPayments = new HashSet<ConnPayment>(0);

    public PaymentType() {
    }

    public PaymentType(String desciption, Set<ConnPayment> connPayments) {
       this.desciption = desciption;
       this.connPayments = connPayments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="desciption", length=100)
    public String getDesciption() {
        return this.desciption;
    }
    
    public void setDesciption(String desciption) {
        this.desciption = desciption;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paymentType")
    public Set<ConnPayment> getConnPayments() {
        return this.connPayments;
    }
    
    public void setConnPayments(Set<ConnPayment> connPayments) {
        this.connPayments = connPayments;
    }




}


