package com.cybercad.billing.domain;
// Generated 13 Aug, 2015 2:58:27 AM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PwdClass generated by hbm2java
 */
@Entity
@Table(name="pwd_class"
    ,catalog="billing"
)
public class PwdClass  implements java.io.Serializable {


     private int id;
     private String description;
     private String code;
     private Integer parentId;
     private Set<Connection> connections = new HashSet<Connection>(0);

    public PwdClass() {
    }

	
    public PwdClass(int id) {
        this.id = id;
    }
    public PwdClass(int id, String description, String code, Integer parentId, Set<Connection> connections) {
       this.id = id;
       this.description = description;
       this.code = code;
       this.parentId = parentId;
       this.connections = connections;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="description", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="code", length=10)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="parent_id")
    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pwdClass")
    public Set<Connection> getConnections() {
        return this.connections;
    }
    
    public void setConnections(Set<Connection> connections) {
        this.connections = connections;
    }




}


